from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer
from rich.table import Table

from modelops_core.ai.agent_loop import run_agent_loop
from modelops_core.commands._common import app, console, _resolve_repo
from modelops_core.config import resolve_model_path
from modelops_core.patching.patch_proposal_service import write_patch_proposal
from modelops_core.pilot import executive_summary as executive_summary_service
from modelops_core.pilot import outcome as pilot_outcome_service
from modelops_core.reports.audit_service import AuditEventService, create_audit_event
from modelops_core.telemetry import with_telemetry


@app.command()
@with_telemetry("propose-patch")
def propose_patch(
    note_file: Path = typer.Option(  # noqa: B008
        ..., "--from", help="Path to note file."
    ),
    repo: str | None = typer.Option(None, "--repo", help="Path to model repository."),
    json_output: bool = typer.Option(False, "--json", help="Output raw JSON."),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Preview proposal without writing files."
    ),
    include_raw_samples: bool = typer.Option(
        False,
        "--include-raw-samples",
        help="Include raw dataset sample values in the AI context (default: redacted).",
    ),
) -> None:
    """Create a PatchProposal from a structured note."""
    repo_root = _resolve_repo(repo)
    model_path = resolve_model_path(repo_root)

    if not note_file.exists():
        console.print(f"[red]Note file not found: {note_file}[/red]")
        raise typer.Exit(code=1)

    note = note_file.read_text(encoding="utf-8")

    if include_raw_samples:
        console.print(
            "[yellow]Warning: raw dataset rows may leave the local environment "
            "depending on provider configuration.[/yellow]"
        )

    from modelops_core.ai.patch_proposal_service import build_patch_proposal_from_note
    from modelops_core.ai.provider_adapter import AIProviderError

    try:
        result = build_patch_proposal_from_note(
            note, repo_root=repo_root, include_raw_samples=include_raw_samples
        )
    except (AIProviderError, ValueError) as exc:
        msg = str(exc)
        if json_output:
            print(
                json.dumps(
                    {
                        "is_safe": False,
                        "proposal": None,
                        "validation": [],
                        "assumptions": [],
                        "human_checks": [f"Patch proposal failed: {msg}"],
                        "error": msg,
                    },
                    indent=2,
                    default=str,
                )
            )
            raise typer.Exit(code=1) from exc
        console.print(f"[red]Patch proposal failed: {msg}[/red]")
        raise typer.Exit(code=1) from exc

    proposal = result.get("proposal")
    if proposal is None:
        if json_output:
            print(json.dumps(result, indent=2, default=str))
        else:
            console.print("[red]No proposal generated.[/red]")
            for assumption in result.get("assumptions", []):
                console.print(f"  • {assumption}")
            for check in result.get("human_checks", []):
                console.print(f"  → {check}")
        raise typer.Exit(code=1)

    path = None
    if not dry_run:
        path = write_patch_proposal(proposal, model_path)

    if json_output:
        result["dry_run"] = dry_run
        print(json.dumps(result, indent=2, default=str))
        return

    if proposal.get("generated_by") == "no_provider_scaffold":
        console.print(
            "[bold yellow]Warning: this proposal was generated by the deterministic "
            "scaffold adapter because no AI provider is configured.[/bold yellow]"
        )
        console.print("[yellow]         Review all operations before approval.[/yellow]")

    if not result.get("is_safe"):
        console.print("[yellow]Proposal generated but failed validation.[/yellow]")

    if dry_run:
        console.print("[bold]Dry-run: proposal preview[/bold]")
    else:
        console.print(f"[green]Patch proposal written to {path}[/green]")
    console.print(f"  ID:    {proposal['id']}")
    console.print(f"  Ops:   {len(proposal.get('operations', []))}")
    console.print(f"  Safe:  {result.get('is_safe')}")

    assumptions = result.get("assumptions", [])
    if assumptions:
        console.print("[bold]Assumptions:[/bold]")
        for a in assumptions:
            console.print(f"  • {a}")

    human_checks = result.get("human_checks", [])
    if human_checks:
        console.print("[bold]Human checks:[/bold]")
        for h in human_checks:
            console.print(f"  • {h}")

    if not dry_run:
        service = AuditEventService(repo_root)
        changed_object_ids = [op.get("object_id", "") for op in proposal.get("operations", [])]
        service.emit(
            create_audit_event(
                event_type="proposal_created",
                actor="system",
                status="success",
                command="propose-patch",
                proposal_id=proposal.get("id"),
                changed_object_ids=changed_object_ids,
                validation_status="valid" if result.get("is_safe") else "invalid",
                outputs={
                    "proposal_id": proposal.get("id"),
                    "operations_count": len(proposal.get("operations", [])),
                    "is_safe": result.get("is_safe"),
                },
            )
        )


@app.command("agent-loop")
@with_telemetry("agent-loop")
def agent_loop(
    goal: str = typer.Option(..., "--goal", help="Free-text modeling goal."),
    repo: str | None = typer.Option(None, "--repo", help="Path to model repository."),
    max_iterations: int = typer.Option(
        5, "--max-iterations", help="Maximum refinement iterations."
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Preview the loop without writing any proposals."
    ),
    json_output: bool = typer.Option(False, "--json", help="Output stable JSON."),
) -> None:
    """Run a closed-loop propose-validate-refine cycle for a modeling goal."""
    repo_root = _resolve_repo(repo)
    model_path = resolve_model_path(repo_root)

    if not model_path.exists():
        console.print(f"[red]Model path does not exist: {model_path}[/red]")
        raise typer.Exit(code=1)

    result = run_agent_loop(
        repo_root=repo_root,
        goal=goal,
        max_iterations=max_iterations,
        dry_run=dry_run,
    )

    if json_output:
        print(json.dumps(result.to_dict(), indent=2, default=str))
        if result.final_status in {"invalid_proposal", "no_progress", "failed"}:
            raise typer.Exit(code=1)
        return

    status_label = result.final_status
    status_color = {
        "valid_proposal": "[green]",
        "high_risk": "[yellow]",
        "invalid_proposal": "[red]",
        "no_progress": "[red]",
        "failed": "[red]",
    }.get(result.final_status, "")

    if dry_run:
        console.print("[bold]Dry-run: agent-loop preview[/bold]")
    console.print(f"{status_color}Status: {status_label}[/]")
    console.print(f"Iterations: {result.iterations}")
    if result.proposal_id:
        console.print(f"Proposal:   {result.proposal_id}")
    if result.proposal_path:
        console.print(f"Path:       {result.proposal_path}")
    if result.validation_status:
        console.print(f"Validation: {result.validation_status}")
    if result.impact:
        console.print(
            f"Impact:     {result.impact.get('affected_objects_count', 0)} affected objects, "
            f"risk={result.impact.get('risk_level', 'unknown')}"
        )

    if result.assumptions:
        console.print("\n[bold]Assumptions:[/bold]")
        for a in result.assumptions:
            console.print(f"  • {a}")

    if result.human_checks:
        console.print("\n[bold]Human checks:[/bold]")
        for h in result.human_checks:
            console.print(f"  • {h}")

    if result.operations_preview:
        console.print("\n[bold]Operations preview:[/bold]")
        preview_table = Table("Operation", "Object", "Status")
        for op in result.operations_preview:
            preview_table.add_row(
                op.get("op", "—"),
                op.get("object_id", "—"),
                op.get("status", "—"),
            )
        console.print(preview_table)

    if result.log:
        console.print("\n[bold]Iteration log:[/bold]")
        table = Table("Iteration", "Action", "Proposal", "Validation")
        for entry in result.log:
            table.add_row(
                str(entry.iteration),
                entry.action,
                entry.proposal_id or "—",
                entry.validation_status or "—",
            )
        console.print(table)

    if result.final_status in {"invalid_proposal", "no_progress", "failed"}:
        raise typer.Exit(code=1)




@app.command("executive-summary")
def executive_summary(
    assessment: Path = typer.Option(  # noqa: B008
        ..., "--assessment", help="Path to assessment manifest.json."
    ),
    out: Path = typer.Option(  # noqa: B008
        ..., "--out", help="Output path or directory for executive summary."
    ),
    json_output: bool = typer.Option(False, "--json", help="Output raw JSON only to stdout."),
) -> None:
    """Generate a one-page executive migration readiness summary."""
    try:
        summary = executive_summary_service.generate_executive_summary(assessment)
    except (FileNotFoundError, ValueError) as exc:
        console.print(f"[red]{exc}[/red]")
        raise typer.Exit(code=1) from exc

    if json_output:
        print(
            json.dumps(
                executive_summary_service.executive_summary_to_dict(summary),
                indent=2,
                default=str,
                sort_keys=True,
            )
        )
        raise typer.Exit()

    executive_summary_service.write_executive_summary(summary, out)
    md_path = out / "executive-summary.md" if out.is_dir() else out.with_suffix(".md")
    console.print(f"[green]Executive summary written to {md_path}[/green]")
    console.print(f"  Verdict: {summary.readiness_verdict}")
    console.print(f"  Confirmed findings: {len(summary.blocking_findings)}")
    console.print(f"  Recommended next action: {summary.recommended_next_action}")


@app.command("pilot-outcome")
@with_telemetry("pilot_outcome")
def pilot_outcome(
    assessment: Path = typer.Option(  # noqa: B008
        ..., "--assessment", help="Path to assessment manifest.json."
    ),
    out: Path = typer.Option(  # noqa: B008
        ..., "--out", help="Output path or directory for the pilot outcome report."
    ),
    json_out: Path | None = typer.Option(  # noqa: B008
        None, "--json-out", help="Optional explicit path for JSON output."
    ),
    baseline_prior_trace_hours: float | None = typer.Option(
        None,
        "--baseline-prior-trace-hours",
        help="Manual baseline for prior trace effort in hours.",
    ),
    baseline_review_hours: float | None = typer.Option(
        None,
        "--baseline-review-hours",
        help="Manual baseline for review effort in hours.",
    ),
    baseline_onboarding_days: float | None = typer.Option(
        None,
        "--baseline-onboarding-days",
        help="Manual baseline for onboarding time in days.",
    ),
) -> None:
    """Generate a pilot outcome report from reviewed assessment findings."""
    if not assessment.exists():
        console.print(f"[red]Assessment manifest not found: {assessment}[/red]")
        raise typer.Exit(code=1)

    baselines: dict[str, Any] = {}
    if baseline_prior_trace_hours is not None:
        baselines["prior_trace_hours"] = baseline_prior_trace_hours
    if baseline_review_hours is not None:
        baselines["review_hours"] = baseline_review_hours
    if baseline_onboarding_days is not None:
        baselines["onboarding_days"] = baseline_onboarding_days

    try:
        outcome = pilot_outcome_service.generate_pilot_outcome(
            assessment,
            baselines=baselines if baselines else None,
        )
        md_path, written_json_path = pilot_outcome_service.write_pilot_outcome(
            outcome, out, json_out_path=json_out
        )
    except (FileNotFoundError, ValueError) as exc:
        console.print(f"[red]{exc}[/red]")
        raise typer.Exit(code=1) from exc

    console.print(f"[green]Pilot outcome written to {md_path}[/green]")
    console.print(f"  Recommendation: {outcome.recommendation}")
    console.print(f"  Confirmed: {outcome.confirmed_findings}")
    console.print(f"  False positives: {outcome.false_positives}")
    if written_json_path:
        console.print(f"  JSON: {written_json_path}")
