/**
 * PatchProposal fixture helpers.
 *
 * These write canonical PatchProposal files directly so that tests can exercise
 * review and apply flows without relying on an AI provider.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { rebuildIndex } from "./repo.js";

/**
 * Render a PatchProposal as Markdown with YAML frontmatter.
 *
 * @param {object} frontmatter
 */
function renderProposal(frontmatter) {
  const yaml = JSON.stringify(frontmatter, null, 2);
  return `---\n${yaml}\n---\n\n# Patch Proposal: ${frontmatter.id}\n`;
}

/**
 * Write a PatchProposal file into the temp repository.
 *
 * @param {string} repoPath
 * @param {string} proposalId
 * @param {object} options
 * @param {string} options.status
 * @param {object[]} options.operations
 * @param {string[]} [options.affectedObjects]
 * @param {string} [options.validationStatus]
 */
export function createProposal(repoPath, proposalId, options) {
  const proposalsDir = path.join(repoPath, "model", "patch-proposals");
  mkdirSync(proposalsDir, { recursive: true });

  const frontmatter = {
    id: proposalId,
    type: "PatchProposal",
    status: options.status,
    name: proposalId,
    title: `Patch Proposal: ${proposalId}`,
    created_by: "workbench-e2e",
    created_at: new Date().toISOString(),
    source_evidence: "Generated by connected e2e test fixture.",
    affected_objects: options.affectedObjects || [],
    operations: options.operations,
    validation_status: options.validationStatus || "pending",
    validation_results: [],
  };

  const filePath = path.join(proposalsDir, `${proposalId}.md`);
  writeFileSync(filePath, renderProposal(frontmatter), "utf-8");
  rebuildIndex(repoPath);
  return filePath;
}

/**
 * Create a proposal that is ready to be reviewed and approved.
 *
 * @param {string} repoPath
 * @param {string} proposalId
 * @param {object[]} [operations]
 */
export function createPendingProposal(
  repoPath,
  proposalId,
  operations = []
) {
  return createProposal(repoPath, proposalId, {
    status: "pending_review",
    operations,
    validationStatus: "passed",
  });
}

/**
 * Create an already-accepted proposal with a low-risk create_object operation.
 *
 * This is used by the apply flow test.
 *
 * @param {string} repoPath
 * @param {string} proposalId
 * @param {object[]} [operations]
 */
export function createAcceptedProposal(
  repoPath,
  proposalId,
  operations = [],
  affectedObjects = []
) {
  return createProposal(repoPath, proposalId, {
    status: "accepted",
    operations,
    affectedObjects,
    validationStatus: "passed",
  });
}

/**
 * Build a low-risk create_object operation for a new Attribute.
 *
 * @param {string} objectId
 * @param {string} name
 * @param {string} domainId
 */
export function createAttributeOperation(objectId, name, domainId) {
  return {
    op: "create_object",
    object_id: objectId,
    object_type: "Attribute",
    after: {
      id: objectId,
      type: "Attribute",
      status: "draft",
      name,
      domain: domainId,
      description: `Connected e2e test attribute: ${name}.`,
      schema_version: "1.0",
      data_steward: "PERSON-DATA-STEWARD",
    },
  };
}

/**
 * Create an approved ChangeRequest linked to a PatchProposal.
 *
 * The apply gate requires an approved ChangeRequest for medium-risk proposals
 * (including most create_object operations for expected owner types).
 *
 * @param {string} repoPath
 * @param {string} crId
 * @param {string} proposalId
 */
export function createApprovedChangeRequest(repoPath, crId, proposalId) {
  const crDir = path.join(repoPath, "model", "change-requests");
  mkdirSync(crDir, { recursive: true });

  const frontmatter = {
    id: crId,
    type: "ChangeRequest",
    status: "approved",
    name: `E2E change request for ${proposalId}`,
    title: `E2E change request for ${proposalId}`,
    created_at: new Date().toISOString(),
    requester: "workbench-e2e",
    reason: "Connected end-to-end test approval.",
    requested_change: "Approve connected e2e proposal.",
    linked_proposals: [proposalId],
    affected_objects: [],
    approvers: ["workbench-e2e"],
    approvals: [{ approver: "workbench-e2e", decision: "approved", approved_at: new Date().toISOString() }],
    approval_status: "approved",
    priority: "medium",
  };

  const filePath = path.join(crDir, `${crId}.md`);
  writeFileSync(filePath, renderProposal(frontmatter), "utf-8");
  rebuildIndex(repoPath);
  return filePath;
}
