export const modelObjects = [
  {
    id: "DOMAIN-CUSTOMER-BP",
    type: "MasterDataDomain",
    label: "Domain",
    name: "Business Partner",
    description:
      "Canonical domain for organizations and people that participate in commercial relationships.",
    fullDescription:
      "Business Partner is the canonical master record for any organization or person with whom the enterprise conducts business. It provides a stable semantic layer above source-system-specific customer and vendor structures, unifying identity, address, tax, and communication data across SAP, CRM, MDM, and analytics platforms.",
    status: "Validated",
    owners: 3,
    updated: "18m ago",
    businessOwner: "Customer Data Office",
    technicalSteward: "Priya Nair",
    lifecycle: "Active",
    lastValidated: "Today, 10:18",
    tags: ["SAP migration", "MDM", "Customer", "Vendor"],
    health: 93,
    systems: ["SAP S/4HANA", "Salesforce CRM", "Informatica MDM", "Customer analytics"],
  },
  {
    id: "ATTR-CUST-ADDRESS-ID",
    type: "Attribute",
    label: "Attribute",
    name: "ADDRESS_ID",
    description: "Unique identifier for the address record associated with a business partner.",
    fullDescription:
      "ADDRESS_ID is the stable identifier for an address record linked to a business partner. It is used to correlate multiple address lines, contact points, and geocoding results across source systems while preserving data lineage back to the originating application.",
    status: "Validated",
    owners: 1,
    updated: "2d ago",
    businessOwner: "Customer Data Office",
    technicalSteward: "Mia Wong",
    lifecycle: "Active",
    lastValidated: "Yesterday, 16:42",
    tags: ["Address", "Identifier", "Customer"],
    health: 98,
    systems: ["SAP S/4HANA", "Salesforce CRM", "Informatica MDM"],
  },
  {
    id: "ATTR-CUST-COUNTRY",
    type: "Attribute",
    label: "Attribute",
    name: "COUNTRY",
    description: "Country or region of the business partner address, standardized to ISO-2.",
    fullDescription:
      "COUNTRY represents the country or region of a business partner address normalized to the ISO-3166-1 alpha-2 standard. It drives tax jurisdiction, regulatory reporting, and regional segmentation and is validated against a controlled value list.",
    status: "Validated",
    owners: 1,
    updated: "2d ago",
    businessOwner: "Customer Data Office",
    technicalSteward: "Priya Nair",
    lifecycle: "Active",
    lastValidated: "Yesterday, 14:20",
    tags: ["Address", "ISO code", "Customer", "Vendor"],
    health: 95,
    systems: ["SAP S/4HANA", "Salesforce CRM", "Customer analytics", "Legacy CRM"],
  },
  {
    id: "ENTITY-CUSTOMER-SALES-AREA",
    type: "BusinessEntity",
    label: "Entity",
    name: "Customer Sales Area",
    description: "Commercial view of a customer at sales organization, channel, and division grain.",
    fullDescription:
      "Customer Sales Area is the commercial view of a customer defined by sales organization, distribution channel, and division. It captures pricing, shipping, and billing conditions and is the primary grain for sales-area-dependent attributes such as customer group and incoterms.",
    status: "In review",
    owners: 2,
    updated: "1h ago",
    businessOwner: "Sales Operations",
    technicalSteward: "Alex Chen",
    lifecycle: "Draft",
    lastValidated: "Today, 09:05",
    tags: ["SAP migration", "Sales", "Customer"],
    health: 78,
    systems: ["SAP S/4HANA", "Salesforce CRM", "Order management"],
  },
  {
    id: "MAP-BP-ADDRESS-STANDARDIZATION",
    type: "Mapping",
    label: "Mapping",
    name: "BP Address Standardization",
    description: "Standardizes source addresses against the canonical Business Partner model.",
    fullDescription:
      "BP Address Standardization defines the transformations required to align source-system address formats with the canonical Business Partner address model. It includes country code normalization, postal code validation, and street-address parsing rules used by the migration pipeline.",
    status: "Validated",
    owners: 2,
    updated: "3d ago",
    businessOwner: "Migration Platform",
    technicalSteward: "Priya Nair",
    lifecycle: "Active",
    lastValidated: "3 days ago, 11:30",
    tags: ["Mapping", "Address", "ETL"],
    health: 91,
    systems: ["SAP S/4HANA", "Informatica MDM", "Legacy CRM"],
  },
  {
    id: "PROPOSAL-27",
    type: "PatchProposal",
    label: "Proposal",
    proposalId: 27,
    name: "Customer alternative key mapping",
    description: "Adds an alternate address key and resolves a high-risk mapping gap.",
    fullDescription:
      "Proposal to add an alternate address key mapping and resolve the high-risk TAX_NUMBER gap by linking SAP field KNVV.STCD1 to the canonical Tax Number attribute with deterministic transform evidence.",
    status: "In review",
    owners: 1,
    updated: "18m ago",
    businessOwner: "Customer Data Office",
    technicalSteward: "Martenweave AI",
    lifecycle: "In review",
    lastValidated: "Today, 10:00",
    tags: ["Proposal", "Tax", "Mapping"],
    health: 88,
    systems: ["SAP S/4HANA", "Sales Order", "Customer analytics"],
  },
];

export const fields = [
  {
    name: "PARTNER_ID",
    id: "ATTR-BP-PARTNER-ID",
    type: "String (40)",
    required: true,
    status: "Validated",
    usage: "8 endpoints",
    description: "Stable business partner identifier across source and target systems.",
  },
  {
    name: "PARTNER_TYPE",
    id: "ATTR-BP-PARTNER-TYPE",
    type: "Code",
    required: true,
    status: "Validated",
    usage: "6 endpoints",
    description: "Organization, person, or group classification.",
  },
  {
    name: "TAX_NUMBER",
    id: "ATTR-BP-TAX-NUMBER",
    type: "String (20)",
    required: false,
    status: "Gap",
    usage: "3 endpoints",
    description: "Tax identification number used for reporting and matching.",
  },
  {
    name: "COUNTRY",
    id: "ATTR-BP-COUNTRY",
    type: "Code (ISO-2)",
    required: true,
    status: "Validated",
    usage: "12 endpoints",
    description: "Country or region of the primary business partner address.",
  },
  {
    name: "LANGUAGE",
    id: "ATTR-BP-LANGUAGE",
    type: "Code (ISO)",
    required: false,
    status: "In review",
    usage: "5 endpoints",
    description: "Preferred language for business communication.",
  },
];

export const gaps = [
  {
    id: 1,
    title: "Missing mapping for TAX_NUMBER",
    severity: "High",
    object: "Business Partner",
    source: "Sales Order (SAP)",
    target: "Business Partner (Canonical)",
    owner: "Priya Nair",
    initials: "PN",
    note: "Tax identification number is not mapped from SAP Sales Order to the canonical model.",
    status: "In review",
    proposal: "Proposal #27",
    proposalId: 27,
    detected: "18m ago",
  },
  {
    id: 2,
    title: "Inconsistent data type: LANGUAGE",
    severity: "Medium",
    object: "Sales Order",
    source: "Sales Order (SAP)",
    target: "Business Partner (Canonical)",
    owner: "Alex Chen",
    initials: "AC",
    note: "LANGUAGE is String in source but ISO code in target. Type standardization is required.",
    status: "Draft",
    proposal: "Proposal #31",
    proposalId: 31,
    detected: "2h ago",
  },
  {
    id: 3,
    title: "Country code standardization",
    severity: "Low",
    object: "Customer",
    source: "Customer (SQL)",
    target: "Business Partner (Canonical)",
    owner: "Mia Wong",
    initials: "MW",
    note: "Country code formats differ between source and target. Standardize to ISO-2.",
    status: "Draft",
    proposal: "Proposal #29",
    proposalId: 29,
    detected: "1h ago",
  },
  {
    id: 4,
    title: "Unmapped field: EMAIL_ADDRESS",
    severity: "High",
    object: "Business Partner",
    source: "Legacy CRM",
    target: "Business Partner (Canonical)",
    owner: "Priya Nair",
    initials: "PN",
    note: "EMAIL_ADDRESS exists in source but is not mapped to target. Contact completeness is at risk.",
    status: "Needs proposal",
    proposal: "—",
    proposalId: null,
    detected: "3h ago",
  },
  {
    id: 5,
    title: "Missing mapping for INDUSTRY",
    severity: "Low",
    object: "Business Partner",
    source: "Customer (SQL)",
    target: "Business Partner (Canonical)",
    owner: "Alex Chen",
    initials: "AC",
    note: "INDUSTRY is absent from the target model. Business segmentation impact is possible.",
    status: "Needs proposal",
    proposal: "—",
    proposalId: null,
    detected: "5h ago",
  },
];

export const proposals = [
  {
    id: 27,
    title: "Customer alternative key mapping",
    summary: "Map KNVV.STCD1 to canonical TAX_NUMBER and add lineage evidence.",
    status: "In review",
    risk: "High",
    author: "Martenweave AI",
    updated: "18m ago",
    changes: 4,
    impactObjects: 2,
    validationStatus: "Passed",
    linkedGap: "Missing mapping for TAX_NUMBER",
    linkedGapId: 1,
  },
  {
    id: 31,
    title: "Normalize business partner language code",
    summary: "Convert legacy language strings to ISO codes and attach the controlled value list.",
    status: "Draft",
    risk: "Medium",
    author: "Alex Chen",
    updated: "2h ago",
    changes: 3,
    impactObjects: 1,
    validationStatus: "Passed",
    linkedGap: "Inconsistent data type: LANGUAGE",
    linkedGapId: 2,
  },
  {
    id: 29,
    title: "Standardize customer country code",
    summary: "Normalize customer country values to ISO-2 before canonical mapping.",
    status: "Draft",
    risk: "Low",
    author: "Mia Wong",
    updated: "1h ago",
    changes: 2,
    impactObjects: 1,
    validationStatus: "Passed",
    linkedGap: "Country code standardization",
    linkedGapId: 3,
  },
];

export const severityWeight = { High: 3, Medium: 2, Low: 1 };

export const recentActivity = [
  ["Validation completed", "Business Partner", "2m ago"],
  ["Proposal #27 updated", "Customer alternative key mapping", "18m ago"],
  ["New gap detected", "TAX_NUMBER", "1h ago"],
  ["Lineage updated", "Sales Order → Business Partner", "2h ago"],
];

export const lineageNodes = [
  {
    id: "salesforce",
    position: { x: 0, y: 120 },
    data: { label: "Salesforce CRM", meta: "Source system", tone: "source" },
    type: "model",
  },
  {
    id: "sap",
    position: { x: 0, y: 300 },
    data: { label: "SAP S/4HANA", meta: "Source system", tone: "source" },
    type: "model",
  },
  {
    id: "staging",
    position: { x: 330, y: 210 },
    data: { label: "BP staging model", meta: "Transformation", tone: "mapping" },
    type: "model",
  },
  {
    id: "canonical",
    position: { x: 670, y: 210 },
    data: { label: "Business Partner", meta: "Canonical model", tone: "canonical" },
    type: "model",
  },
  {
    id: "mdm",
    position: { x: 1010, y: 100 },
    data: { label: "Informatica MDM", meta: "Target system", tone: "target" },
    type: "model",
  },
  {
    id: "analytics",
    position: { x: 1010, y: 320 },
    data: { label: "Customer analytics", meta: "Downstream dataset", tone: "target" },
    type: "model",
  },
];

export const lineageEdges = [
  { id: "e1", source: "salesforce", target: "staging", animated: true },
  { id: "e2", source: "sap", target: "staging", animated: true },
  { id: "e3", source: "staging", target: "canonical", animated: true },
  { id: "e4", source: "canonical", target: "mdm" },
  { id: "e5", source: "canonical", target: "analytics" },
];
