"""Generate GitHub-ready Markdown issue drafts from model artifacts."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

from modelops_core.approval import assess_change_request, compute_proposal_risk
from modelops_core.change_request.service import load_change_request
from modelops_core.config import resolve_generated_path, resolve_model_path
from modelops_core.impact.proposal_impact_service import generate_proposal_impact_report
from modelops_core.repository import parse_file, scan_repository
from modelops_core.validation import validate_objects


class DraftSource(StrEnum):
    """Supported sources for issue draft generation."""

    CHANGE_REQUEST = "change_request"
    PROPOSAL = "proposal"
    VALIDATION = "validation"
    ANALYSIS = "analysis"


@dataclass
class DraftResult:
    """Result of generating an issue draft."""

    title: str
    body: str
    source_type: str
    source_id: str | None = None
    labels: list[str] = field(default_factory=list)
    suggested_assignees: list[str] = field(default_factory=list)


def _now_iso() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _fm_string(value: Any) -> str:
    """Safely convert frontmatter value to string."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value)


def create_draft_from_change_request(model_path: Path, cr_id: str) -> DraftResult:
    """Generate an issue draft from a ChangeRequest."""
    cr = load_change_request(model_path, cr_id)
    if cr is None:
        raise ValueError(f"ChangeRequest not found: {cr_id}")

    risk = assess_change_request(cr, model_path)

    title = f"[ChangeRequest] {cr.get('title') or cr.get('name') or cr_id}"
    lines: list[str] = []

    lines.append("## Goal")
    lines.append(
        cr.get("reason")
        or cr.get("requested_change")
        or f"Review and approve ChangeRequest {cr_id}."
    )
    lines.append("")

    if cr.get("requested_change"):
        lines.append("### Requested Change")
        lines.append(cr["requested_change"])
        lines.append("")

    if cr.get("expected_impact"):
        lines.append("### Expected Impact")
        lines.append(cr["expected_impact"])
        lines.append("")

    affected = cr.get("affected_objects") or []
    if affected:
        lines.append("### Affected Objects")
        for obj_id in affected:
            lines.append(f"- `{obj_id}`")
        lines.append("")

    linked = cr.get("linked_proposals") or []
    if linked:
        lines.append("### Linked Proposals")
        for pid in linked:
            lines.append(f"- `{pid}`")
        lines.append("")

    approvers = cr.get("approvers") or []
    if approvers:
        lines.append("### Required Approvers")
        for a in approvers:
            lines.append(f"- @{a}")
        lines.append("")

    lines.append("### Risk Assessment")
    lines.append(f"- **Level:** {risk.risk_level}")
    if risk.requires_approval:
        lines.append("- **Approval required:** yes")
        for reason in risk.risk_reasons:
            lines.append(f"  - {reason}")
    else:
        lines.append("- **Approval required:** no")
    lines.append("")

    lines.append("### Suggested Next Action")
    if risk.requires_approval:
        lines.append(
            "1. Review affected objects and linked proposals.\n"
            "2. Confirm approvers are available.\n"
            "3. Run `martenweave change-request approve {cr_id} --approver <id>`."
        )
    else:
        lines.append(
            "1. Review the change for completeness.\n"
            "2. Proceed with lightweight implementation if validation passes."
        )
    lines.append("")

    lines.append("---")
    lines.append(f"*Generated by martenweave at {_now_iso()}*")

    suggested = list(approvers)
    if cr.get("requester"):
        suggested.append(cr["requester"])

    labels = ["change-request"]
    if risk.risk_level == "high":
        labels.append("high-risk")

    return DraftResult(
        title=title,
        body="\n".join(lines),
        source_type=DraftSource.CHANGE_REQUEST,
        source_id=cr_id,
        labels=labels,
        suggested_assignees=list(dict.fromkeys(suggested)),
    )


def create_draft_from_proposal(
    model_path: Path,
    generated_path: Path,
    proposal_id: str,
) -> DraftResult:
    """Generate an issue draft from a PatchProposal."""
    proposal_path = model_path / "patch-proposals" / f"{proposal_id}.md"
    if not proposal_path.exists():
        raise ValueError(f"PatchProposal not found: {proposal_id}")

    parsed = parse_file(proposal_path)
    fm = parsed.frontmatter or {}

    operations = fm.get("operations", [])
    risk = compute_proposal_risk(operations, model_path)

    # Compute impact if index exists
    db_path = generated_path / "modelops.db"
    impact_objects: list[dict[str, Any]] = []
    if db_path.exists():
        try:
            impact_report = generate_proposal_impact_report(
                db_path, proposal_id, operations, max_depth=2
            )
            impact_objects = [
                {
                    "object_id": obj.object_id,
                    "object_type": obj.object_type,
                    "direction": obj.direction,
                    "depth": obj.depth,
                }
                for obj in impact_report.all_affected_objects[:20]
            ]
        except Exception:
            pass

    title = f"[PatchProposal] {fm.get('title') or fm.get('name') or proposal_id}"
    lines: list[str] = []

    lines.append("## Goal")
    lines.append(
        fm.get("source_evidence") or f"Review PatchProposal {proposal_id} before application."
    )
    lines.append("")

    lines.append("### Operations")
    for op in operations[:20]:
        obj_id = op.get("object_id", "—")
        op_type = op.get("op", "—")
        target = op.get("target_path", "—")
        lines.append(f"- `{op_type}` → `{obj_id}` ({target})")
    if len(operations) > 20:
        lines.append(f"- ... and {len(operations) - 20} more operations")
    lines.append("")

    affected = fm.get("affected_objects") or []
    if affected:
        lines.append("### Affected Objects")
        for obj_id in affected[:30]:
            lines.append(f"- `{obj_id}`")
        if len(affected) > 30:
            lines.append(f"- ... and {len(affected) - 30} more")
        lines.append("")

    if impact_objects:
        lines.append("### Impact Summary")
        for obj in impact_objects:
            lines.append(
                f"- `{obj['object_id']}` ({obj['object_type'] or 'Unknown'}) "
                f"— {obj['direction']} depth {obj['depth']}"
            )
        lines.append("")

    lines.append("### Risk Assessment")
    lines.append(f"- **Level:** {risk.risk_level}")
    if risk.requires_approval:
        lines.append("- **Approval required:** yes")
        for reason in risk.risk_reasons:
            lines.append(f"  - {reason}")
    else:
        lines.append("- **Approval required:** no")
    lines.append("")

    lines.append("### Validation Status")
    lines.append(f"- Status: {fm.get('validation_status', 'unknown')}")
    lines.append("")

    lines.append("### Suggested Next Action")
    if risk.requires_approval:
        lines.append(
            "1. Review operations and impact.\n"
            "2. Create a ChangeRequest linking to this proposal.\n"
            "3. Obtain approval before applying.\n"
            "4. Run `martenweave proposal apply {proposal_id} --apply`."
        )
    else:
        lines.append(
            "1. Validate the proposal.\n"
            "2. Run `martenweave proposal apply {proposal_id} --apply` if acceptable."
        )
    lines.append("")

    lines.append("---")
    lines.append(f"*Generated by martenweave at {_now_iso()}*")

    labels = ["patch-proposal"]
    if risk.risk_level == "high":
        labels.append("high-risk")

    return DraftResult(
        title=title,
        body="\n".join(lines),
        source_type=DraftSource.PROPOSAL,
        source_id=proposal_id,
        labels=labels,
        suggested_assignees=[],
    )


def create_draft_from_validation(
    repo_root: Path,
) -> DraftResult:
    """Generate an issue draft from current validation results."""
    model_path = resolve_model_path(repo_root)
    files = scan_repository(model_path)
    parsed_objects = [parse_file(f) for f in files]
    summary = validate_objects(parsed_objects)

    errors = [r for r in summary.results if r.severity == "ERROR"]
    warnings = [r for r in summary.results if r.severity == "WARNING"]

    title = "[Validation] Model validation issues"
    lines: list[str] = []

    lines.append("## Goal")
    lines.append("Address validation issues found in the model repository.")
    lines.append("")

    lines.append("### Summary")
    lines.append(f"- Errors: {len(errors)}")
    lines.append(f"- Warnings: {len(warnings)}")
    lines.append("")

    if errors:
        lines.append("### Errors")
        for r in errors[:30]:
            lines.append(f"- `{r.object_id or '—'}` — {r.code}: {r.message}")
            if r.suggested_fix:
                lines.append(f"  - *Fix:* {r.suggested_fix}")
        if len(errors) > 30:
            lines.append(f"- ... and {len(errors) - 30} more errors")
        lines.append("")

    if warnings:
        lines.append("### Warnings")
        for r in warnings[:30]:
            lines.append(f"- `{r.object_id or '—'}` — {r.code}: {r.message}")
            if r.suggested_fix:
                lines.append(f"  - *Fix:* {r.suggested_fix}")
        if len(warnings) > 30:
            lines.append(f"- ... and {len(warnings) - 30} more warnings")
        lines.append("")

    lines.append("### Suggested Next Action")
    lines.append(
        "1. Review errors and warnings above.\n"
        "2. Fix individual objects or create PatchProposals.\n"
        "3. Re-run `martenweave validate` to confirm resolution."
    )
    lines.append("")

    lines.append("---")
    lines.append(f"*Generated by martenweave at {_now_iso()}*")

    labels = ["validation"]
    if errors:
        labels.append("bug")

    return DraftResult(
        title=title,
        body="\n".join(lines),
        source_type=DraftSource.VALIDATION,
        labels=labels,
        suggested_assignees=[],
    )


def write_draft(repo_root: Path, draft: DraftResult, output_path: Path | None = None) -> Path:
    """Write a draft to disk. Returns the path written."""
    if output_path is None:
        output_dir = resolve_generated_path(repo_root) / "issues"
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{draft.source_type}"
        if draft.source_id:
            filename = f"{draft.source_id}"
        output_path = output_dir / f"{filename}.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)

    frontmatter_lines = [
        "---",
        f'title: "{draft.title}"',
        f"labels: [{', '.join(draft.labels)}]",
    ]
    if draft.suggested_assignees:
        frontmatter_lines.append(f"assignees: [{', '.join(draft.suggested_assignees)}]")
    frontmatter_lines.append("---")
    frontmatter_lines.append("")

    output_path.write_text(
        "\n".join(frontmatter_lines) + draft.body,
        encoding="utf-8",
    )
    return output_path
